---
title: "Untitled"
author:
- name: Kieran Healy
  affiliation: Duke University
  email: kjhealy@soc.duke.edu
date: '`r format(Sys.Date(), "%B %d, %Y")`'
crossrefYaml: "config/pandoc-crossref-settings.yaml"
output:
  pdf_document: 
    md_extensions: +simple_tables+table_captions+yaml_metadata_block+smart
    template: /Users/kjhealy/.pandoc/templates/rmd-latex.template
    pandoc_args: [
      "--bibliography", "/Users/kjhealy/Documents/bibs/socbib-pandoc.bib",
      "--filter", "pandoc-crossref",
      "--filter", "pandoc-citeproc",
      "--csl", "/Users/kjhealy/.pandoc/csl/ajps.csl",
      "--filter", "pandoc-citeproc-preamble", 
      "-M", "citeproc-preamble=config/preamble.tex"
      ]      
  html_document: radix::radix_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}

library(tidyverse)
library(janitor)
library(socviz)
library(ggrepel)

## --------------------------------------------------------------------
## Custom font and theme, omit if you don't have the myriad library
## (https://github.com/kjhealy/myriad) and associated Adobe fonts.
## --------------------------------------------------------------------
library(showtext)
showtext_auto()
library(myriad)
import_myriad_semi()

theme_set(theme_myriad_semi())

### --------------------------------------------------------------------

```

## Introduction
